export enum WaitMethods {
    get = 'GET',
    post = 'POST',
    delete = 'DELETE',
    put = 'PUT',
  }
  
  export enum CommonGetLocators {
    iconuserid = 'icon-user',
    userSettingsMenuId = 'userSettingsMenu',
    settings = 'Application Settings',
    adminSearchId = '#adminconfig_search',
    ambulatoryId = 'org-name-29',
    toggleId = '.accordion-toggle',
    addId = '#btn_Add_',
    buttonId = '#accp_popup_done',
    generalId = '#General_aval_btn',
    defaultId = '#General_def_btn',
    consentsId = '#addConsents',
    dashedBorderId = '.dashed-border-box-add-button',
    resultId = '.cke_wysiwyg_div.cke_reset.cke_enable_context_menu.cke_editable.cke_editable_themed.cke_contents_ltr.cke_show_borders',
    selectVariableId = '.pull-left',
    dicId = '.dictionaryItem',
    inserId = '.button-primary-small',
    patientSearchId = 'patient-search-bar-input',
    pntAcntId = 'patient-search-result-account-number',
    cnstIconId = '#cdetails_consents_icon',
    cnstButnId = '#btn_add_consent_case',
    allTxtId = '.ng-binding',
    txtSrchId = '#txt_sltpu_search',
    lstSrchId = '.list-group.list-check-list',
    flexGrwId = '.flex-grow',
    btnDoneId = '#btn_sltpu_done',
    defaultImageId = '.fa.fa-user.user-default-image.pull-left',
    logoutid = '#logout',
    yesbtnId = '#btn_lop_yes',
    consentBtnId = '#Consents_btn',
    modalbndgId = '.modal-title.ng-binding',
    consentConfgId = '#consent_configuration_name',
    paindefId='#Pain_def_btn',
    painavilId = '#Pain_aval_btn',
    enableId = 'be.enabled',
    havecssId = 'have.css',
    bckgrndId = 'background-color',
    havevalueId = 'have.value',
    tittlengbidgId = '.title.ng-binding',
    decminalTextId= '#decimalTextBox_copt_expireInDays_dtb',
    errorId = '.error',
    ngBindId = '.ng-binding.ng-scope',
    flxGrwId = '.flex-grow.ng-binding',
    consentConfigId = '#consent_configuration_name',
    deleteIconId = '.fa.fa-times-circle.pull-right.delete-icon.ng-scope',
    errorBindId = '.error-message.ng-binding.ng-scope',
    bttnScndryId = '.button-secondary-small'
  
  }